services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - TUNNEL_TOKEN=${TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      - cloudflarednetwork

networks:
  cloudflarednetwork:
    name: cloudflared   